### ISSUE TITLE
FeatureScopeable should only be resolved in Feature::serializeScope

### ISSUE THREAD

**Issue by alaaemadelsayed** [laravel/pennant#124] opened 2024-10-25 20:11 UTC
### Pennant Version

1.12.0

### Laravel Version

12

### PHP Version

8

### Description

As of right now, there's no way to create a custom scope that both gets passed as is to the resolver and gets serialized as a string. Either the scope is one of the supported serializable types (string, number, Model) and gets passed as is to the resolver. Or it implements FeatureScopeable and is passed down as one of those types anyway.

FeatureScopeable is useful for mapping to special scopes based on drivers, but doesn't solve this issue. Maybe a solution would be for the serialize method to support Serializable types. Only solution right now as far as I know is a custom driver that augments scope serialization. #

### Steps To Reproduce

As mentioned in the description

**Comment by timacdonald** [comment] 2024-10-27 22:11
Duplicate of https://github.com/laravel/pennant/issues/97.

Think I'll take a look at solving this after Laracon AU. It has come up a few times and can see it being useful.

**Comment by timacdonald** [comment] 2024-11-06 05:49
Opened a PR to handle this: https://github.com/laravel/pennant/pull/125

**Closed as completed by timacdonald** 2024-11-06 05:49 UTC
